apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: {{ .Values.backend.resources.maxCpu }}
              memory: {{ .Values.backend.resources.maxMemory }}
            requests:
              cpu: {{ .Values.backend.resources.minCpu }}
              memory: {{ .Values.backend.resources.minMemory }}
          env:
            - name: DB_USER
              value: {{ .Values.backend.env.DB_USER }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: DB-PASSWORD
            - name: DB_DATABASE
              value: {{ .Values.backend.env.DB_DATABASE }}
            - name: DB_HOST
              value: {{ .Release.Name }}-postgres-service
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.healthCheckPath }}
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
